import { defineEventHandler } from "h3";

export default defineEventHandler(() =>
  [
    {
      id: 1,
      name: "Java",
      category: 1,
      skill: 90,
      icon: "devicon:java",
    },
    {
      id: 2,
      name: "C#",
      category: 1,
      skill: 90,
      icon: "devicon:csharp",
    },
    {
      id: 3,
      name: "JavaScript",
      category: 1,
      skill: 90,
      icon: "devicon:javascript",
    },
    {
      id: 4,
      name: "TypeScript",
      category: 1,
      skill: 90,
      icon: "devicon:typescript",
    },
    {
      id: 5,
      name: "Python",
      category: 1,
      skill: 95,
      icon: "devicon:python",
    },
    {
      id: 6,
      name: "C++",
      category: 1,
      skill: 70,
      icon: "devicon:cplusplus",
    },
    {
      id: 7,
      name: "C",
      category: 1,
      skill: 70,
      icon: "devicon:c",
    },
    {
      id: 8,
      name: "SQL",
      category: 3,
      skill: 65,
      icon: "devicon:sqlite",
    },
    {
      id: 9,
      name: "Vue",
      category: 4,
      skill: 65,
      icon: "devicon:vuejs",
    },
    {
      id: 10,
      name: "Angular",
      category: 4,
      skill: 50,
      icon: "devicon:angular",
    },
    {
      id: 11,
      name: "Azure DevOps",
      category: 2,
      skill: 80,
      icon: "devicon:azuredevops",
    },
    {
      id: 12,
      name: "Git",
      category: 2,
      skill: 70,
      icon: "devicon:git",
    },
    {
      id: 13,
      name: "GitHub Actions",
      category: 2,
      skill: 80,
      icon: "devicon:githubactions",
    },
    {
      id: 14,
      name: "Ballerina",
      category: 1,
      skill: 60,
      icon: "devicon:ballerina",
    },
    {
      id: 15,
      name: "Cloudflare",
      category: 2,
      skill: 40,
      icon: "devicon:cloudflare",
    },
    {
      id: 16,
      name: "Docker",
      category: 2,
      skill: 70,
      icon: "devicon:docker",
    },
    {
      id: 17,
      name: "Podman",
      category: 2,
      skill: 70,
      icon: "devicon:podman",
    },

    {
      id: 18,
      name: "Cypress",
      category: 6,
      skill: 80,
      icon: "devicon:cypressio",
    },
    {
      id: 19,
      name: "Mongodb",
      category: 3,
      skill: 70,
      icon: "devicon:mongodb",
    },
    {
      id: 20,
      name: "Rust",
      category: 1,
      skill: 100,
      icon: "devicon:rust",
    },
    {
      id: 21,
      name: "Ansible",
      category: 2,
      skill: 65,
      icon: "devicon:ansible",
    },
    {
      id: 22,
      name: "Postman",
      category: 6,
      skill: 50,
      icon: "devicon:postman",
    },
    {
      id: 23,
      name: "Bash",
      category: 1,
      skill: 65,
      icon: "devicon:bash",
    },
  ].sort((a, b) => b.skill - a.skill),
);
