name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Ensure Playwright Browsers Installed
      run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'


    - name: Install Playwright Browsers
      run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Running Playwright tests on Preview
      run: npx playwright test
      if: github.ref_name == 'develop' || github.base_ref == 'develop' || github.base_ref == 'main'
      env:
        NUXT_PUBLIC_SITE_URL: ${{ secrets.PREVIEW_URL }}

    - name: Running Playwright tests on Main
      run: npx playwright test
      if: github.ref_name == 'main' && github.event.pull_request.merged == true
      env:
        NUXT_PUBLIC_SITE_URL: ${{ vars.SITE_URL }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
